<h3>Novo Livro</h3>


<?php

$form=$this->form;

$form->setAttribute('action', $this->url('livraria-admin', array('controller'=>'livros', 'action'=>'new')));



$form->prepare();
echo $this->form()->openTag($form);
echo  $this->formHidden($form->get('id'))."</br></br>";
echo $this->formRow($form->get('nome'))."</br></br>";
echo $this->formRow($form->get('autor'))."</br></br>";
echo $this->formRow($form->get('categoria'))."</br></br>";
echo $this->formRow($form->get('isbn'))."</br></br>";
echo $this->formRow($form->get('valor'))."</br></br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->CloseTag();

?>