<h1>Categorias</h1>
<p><a href="<?php echo $this->url('livraria-admin', array('controller'=>'categorias', 'action'=>'new'));?>">Novo</a></a></p>
<table class="table">
    <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Ação</th>
    </tr>

    <tr>
        <?php foreach($this->data as $categoria): ?>
        <td><?php echo $categoria->getId(); ?></td>
        <td><?php echo $categoria->getNome(); ?></td>
        <td>
            <a href="<?php echo $this->url('livraria-admin-interna', array('controller'=>'categorias', 'action'=>'edit', 'id'=>$categoria->getId())); ?>">Editar</a>
            <a href="<?php echo $this->url('livraria-admin-interna', array('controller'=>'categorias', 'action'=>'delete', 'id'=>$categoria->getId())); ?>">Deletar</a>


        </td>

    </tr>
    <?php endforeach; ?>
</table>
<br/>
<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>

