<h1>Categorias</h1>

<table class="table">
    <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Ação</th>
    </tr>

    <tr>
        <?php foreach($this->data as $categoria): ?>
        <td><?php echo $categoria->getId(); ?></td>
        <td><?php echo $categoria->getNome(); ?></td>
        <td></td>

    </tr>
    <?php endforeach; ?>
</table>
<br/>
<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>

